"""Add autoinc

Revision ID: 405428ba6eb5
Revises: 
Create Date: 2024-02-24 21:20:09.539119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405428ba6eb5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pk_post_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('date_posted', sa.DateTime(), nullable=False))
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.alter_column('post_img',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=300),
               existing_nullable=True)
        batch_op.drop_column('id')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pk_user_id', sa.Integer(), autoincrement=True, nullable=False))
        batch_op.add_column(sa.Column('uq_username', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=120), nullable=False))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['uq_username'])
        batch_op.drop_column('id')
        batch_op.drop_column('username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(length=80), nullable=True))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('password')
        batch_op.drop_column('uq_username')
        batch_op.drop_column('pk_user_id')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))
        batch_op.alter_column('post_img',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
        batch_op.drop_column('date_posted')
        batch_op.drop_column('pk_post_id')

    # ### end Alembic commands ###
